apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-clusterrole
rules:
- apiGroups: ["", "apps", "batch", "extensions", "rbac.authorization.k8s.io", "operator.victoriametrics.com", "admissionregistration.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: github-runner-clusterrole
  apiGroup: rbac.authorization.k8s.io